#
#  Do not edit this file.  This file is generated from 
#  package.bld.  Any modifications to this file will be 
#  overwritten whenever makefiles are re-generated.
#
#  target compatibility key = ti.targets.msp430.elf.MSP430X{1,0,4.4,3
#
main.xe430X: package/cfg/main.xe430X.mak

clean::
	-$(RM) package/cfg/main.xe430X.mak
