/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_10_00_82/packages/ti/mcu/msp430/csl2/communication/EUSCI_init.xdt
 */
#include <stdint.h>
#include "_Grace.h"
#include <driverlib/MSP430FR57xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR57xx/eusci_b_i2c.h>

/* USER CODE START (section: EUSCI_B0_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: EUSCI_B0_init_c_prologue) */

/*
 *  ======== EUSCI_B0_graceInit ========
 *  Initialize Config for the MSP430 EUSCI_B0
 */
void EUSCI_B0_graceInit(void)
{
    /* Struct to pass to EUSCI_B_I2C_initMaster */
    EUSCI_B_I2C_initMasterParam initI2CMasterParam = {0};

    /* USER CODE START (section: EUSCI_B0_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: EUSCI_B0_graceInit_prologue) */


    /* initialize I2C master mode */
    initI2CMasterParam.selectClockSource = EUSCI_B_I2C_CLOCKSOURCE_SMCLK;
    initI2CMasterParam.i2cClk = 2000000;
    initI2CMasterParam.dataRate = EUSCI_B_I2C_SET_DATA_RATE_400KBPS;
    initI2CMasterParam.byteCounterThreshold = 0;
    initI2CMasterParam.autoSTOPGeneration = EUSCI_B_I2C_NO_AUTO_STOP;
    EUSCI_B_I2C_initMaster(EUSCI_B0_BASE, &initI2CMasterParam);

    /* set mode of I2C */
    EUSCI_B_I2C_setMode(EUSCI_B0_BASE, EUSCI_B_I2C_TRANSMIT_MODE);

    /* set the address that I2C master will place on the bus */
    EUSCI_B_I2C_setSlaveAddress(EUSCI_B0_BASE, 0);

    /* enable I2C */
    EUSCI_B_I2C_enable(EUSCI_B0_BASE);

    /* disable interrupt EUSCI_B_I2C_TRANSMIT_INTERRUPT0 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_TRANSMIT_INTERRUPT0);

    /* disable interrupt EUSCI_B_I2C_RECEIVE_INTERRUPT0 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_RECEIVE_INTERRUPT0);

    /* disable interrupt EUSCI_B_I2C_TRANSMIT_INTERRUPT1 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_TRANSMIT_INTERRUPT1);

    /* disable interrupt EUSCI_B_I2C_RECEIVE_INTERRUPT1 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_RECEIVE_INTERRUPT1);

    /* disable interrupt EUSCI_B_I2C_TRANSMIT_INTERRUPT2 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_TRANSMIT_INTERRUPT2);

    /* disable interrupt EUSCI_B_I2C_RECEIVE_INTERRUPT2 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_RECEIVE_INTERRUPT2);

    /* disable interrupt EUSCI_B_I2C_TRANSMIT_INTERRUPT3 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_TRANSMIT_INTERRUPT3);

    /* disable interrupt EUSCI_B_I2C_RECEIVE_INTERRUPT3 */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_RECEIVE_INTERRUPT3);

    /* disable interrupt EUSCI_B_I2C_START_INTERRUPT */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_START_INTERRUPT);

    /* disable interrupt EUSCI_B_I2C_STOP_INTERRUPT */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_STOP_INTERRUPT);

    /* disable interrupt EUSCI_B_I2C_NAK_INTERRUPT */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_NAK_INTERRUPT);

    /* disable interrupt EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_ARBITRATIONLOST_INTERRUPT);

    /* disable interrupt EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT */
    EUSCI_B_I2C_disableInterrupt(EUSCI_B0_BASE, EUSCI_B_I2C_CLOCK_LOW_TIMEOUT_INTERRUPT);

    /* USER CODE START (section: EUSCI_B0_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: EUSCI_B0_graceInit_epilogue) */

}
