/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_3_10_00_82/packages/ti/mcu/msp430/csl2/clock/CS_init.xdt
 */
#include <driverlib/MSP430FR57xx/inc/hw_memmap.h>
#include <driverlib/MSP430FR57xx/cs.h>
#include "_Grace.h"

/* USER CODE START (section: CS_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: CS_init_c_prologue) */

/*
 *  ======== CS_graceInit ========
 *  Initialize MSP430 Clock System
 */
void CS_graceInit(void)
{

    /* USER CODE START (section: CS_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: CS_graceInit_prologue) */

    /*
     * Set DCO frequency to 8000000 Hz
     */
    CS_setDCOFreq(CS_DCORSEL_0, CS_DCOFSEL_3);

    /*
     * Setting MCLK source from CS_DCOCLK_SELECT with the divider of CS_CLOCK_DIVIDER_2.
     */
    CS_initClockSignal(CS_MCLK, CS_DCOCLK_SELECT, CS_CLOCK_DIVIDER_2);

    /*
     * Setting SMCLK source from CS_DCOCLK_SELECT with the divider of CS_CLOCK_DIVIDER_4.
     */
    CS_initClockSignal(CS_SMCLK, CS_DCOCLK_SELECT, CS_CLOCK_DIVIDER_4);

    /*
     * Setting ACLK source from CS_VLOCLK_SELECT with the divider of CS_CLOCK_DIVIDER_1.
     */
    CS_initClockSignal(CS_ACLK, CS_VLOCLK_SELECT, CS_CLOCK_DIVIDER_1);

    /*
     * Clears all oscillator fault flags including global oscillator fault flag
     * before switching clock sources
     */
    CS_clearAllOscFlagsWithTimeout(100000);




    /* USER CODE START (section: CS_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: CS_graceInit_epilogue) */
}
